### ISSUE TITLE
[SUGGESTION] Update to ReScript 10

### ISSUE THREAD

**Issue by davisuga** [reck753/rescript-reanimated#4]
The new ReScript version has optional record fields, which I believe that would be very useful.

**Comment by reck753** [comment]
> The new ReScript version has optional record fields, which I believe that would be very useful.

Hi @davisuga 👋
Thanks on posting!

It can be very useful! I will try to do it in the next few days, alongside few more things. I will probably leave the `make*` functions as well, for those which like more functional approach 😆
